version: "3.7"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    container_name: ${APP_NAME}_nginx_${APP_ENV}
    environment:
      - FASTCGI_PASS=${APP_NAME}_php_${APP_ENV}:9000
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: php/${APP_ENV:-local}/Dockerfile
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    ports:
      - '5173:5173' # Vite port
    container_name: ${APP_NAME}_php_${APP_ENV}
  mysql:
    networks:
      - internal
    image: 'mysql:latest'
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    container_name: ${APP_NAME}_mysql_${APP_ENV}
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - internal
    container_name: ${APP_NAME}_redis_${APP_ENV}
networks:
  internal:
    driver: bridge
