version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/production/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    container_name: ${APP_NAME}_nginx_${APP_ENV}
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: php/production/Dockerfile
    networks:
      - internal
    container_name: ${APP_NAME}_php_${APP_ENV}
    depends_on:
      - mysql
      - redis
  mysql:
    networks:
      - internal
    image: 'mysql:latest'
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: 'root'
    container_name: ${APP_NAME}_mysql_${APP_ENV}
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - internal
    container_name: ${APP_NAME}_redis_${APP_ENV}
networks:
  internal:
    driver: bridge
