version: "3.7"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/staging/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
      - ./nginx/staging/default.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx_staging
  php:
    build:
      context: .
      dockerfile: php/staging/Dockerfile
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    container_name: php_staging
  mysql:
    networks:
      - internal
    image: 'mysql:latest'
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: 'root'
    container_name: mysql_staging
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - internal
    container_name: redis_staging
networks:
  internal:
    driver: bridge
